# Generated by Django 6.1 on 2026-08-28 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('train_type', models.CharField(choices=[('EXPRESS', 'Express'), ('SUPERFAST', 'Superfast'), ('PASSENGER', 'Passenger'), ('SPECIAL', 'Special')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_number', models.PositiveIntegerField()),
                ('distance_from_source', models.DecimalField(decimal_places=2, max_digits=8)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_routes', to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trains.train')),
            ],
        ),
    ]
