# Generated by Django 6.1 on 2026-09-02 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='destination_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_trains', to='trains.station'),
        ),
        migrations.AddField(
            model_name='train',
            name='source_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_trains', to='trains.station'),
        ),
        migrations.CreateModel(
            name='TrainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='trains.train')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DELAY', 'Delay'), ('CANCELLATION', 'Cancellation'), ('UNEXPECTED_STOP', 'Unexpected Stop'), ('SPEED', 'Speed Alert'), ('NO_DATA', 'No Data')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('train_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trains.trainrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('scheduled_arrival', models.TimeField(blank=True, null=True)),
                ('scheduled_departure', models.TimeField(blank=True, null=True)),
                ('distance_from_source', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='train_stops', to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trains.train')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TrainPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bearing', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField()),
                ('train_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trains.trainrun')),
                ('current_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_positions', to='trains.trainstop')),
                ('next_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_positions', to='trains.trainstop')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddConstraint(
            model_name='trainrun',
            constraint=models.UniqueConstraint(fields=('train', 'journey_date'), name='unique_train_run_per_day'),
        ),
        migrations.AddConstraint(
            model_name='trainstop',
            constraint=models.UniqueConstraint(fields=('train', 'sequence'), name='unique_train_stop_sequence'),
        ),
    ]
